// <auto-generated />
using System;
using GateKeep.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GateKeep.Api.Migrations
{
    [DbContext(typeof(GateKeepDbContext))]
    partial class GateKeepDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.Anuncio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_anuncios_fecha");

                    b.ToTable("anuncios", (string)null);
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.Beneficio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Cupos")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaDeVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("beneficios", (string)null);
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.BeneficioUsuario", b =>
                {
                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<long>("BeneficioId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EstadoCanje")
                        .HasColumnType("boolean");

                    b.HasKey("UsuarioId", "BeneficioId");

                    b.HasIndex("BeneficioId")
                        .HasDatabaseName("IX_beneficios_usuarios_beneficio_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_beneficios_usuarios_usuario_id");

                    b.ToTable("beneficios_usuarios", (string)null);
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.DispositivoSync", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Plataforma")
                        .HasColumnType("text");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UltimaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<string>("VersionCliente")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DispositivosSync");
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.Espacio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("IX_espacios_activo");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_espacios_nombre");

                    b.ToTable("espacios", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.Evento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PuntoControl")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_eventos_fecha");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.EventoAcceso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EspacioId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PuntoControl")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EspacioId")
                        .HasDatabaseName("IX_eventos_acceso_espacio_id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_eventos_acceso_fecha");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_eventos_acceso_usuario_id");

                    b.ToTable("eventos_acceso", (string)null);
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.EventoOffline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DatosEvento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacionCliente")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("IdEventoPermanente")
                        .HasColumnType("bigint");

                    b.Property<string>("IdTemporal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IntentosProcessamiento")
                        .HasColumnType("integer");

                    b.Property<string>("MensajeError")
                        .HasColumnType("text");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EventosOffline");
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.ReglaAcceso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<long>("EspacioId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("HorarioApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HorarioCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RolesPermitidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("VigenciaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("VigenciaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EspacioId")
                        .HasDatabaseName("IX_reglas_acceso_espacio_id");

                    b.ToTable("reglas_acceso", (string)null);
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Credencial")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Credencial")
                        .HasDatabaseName("IX_usuarios_credencial");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_usuarios_email");

                    b.HasIndex("Rol")
                        .HasDatabaseName("IX_usuarios_rol");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.UsuarioEspacio", b =>
                {
                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<long>("EspacioId")
                        .HasColumnType("bigint");

                    b.HasKey("UsuarioId", "EspacioId");

                    b.HasIndex("EspacioId")
                        .HasDatabaseName("IX_usuarios_espacios_espacio_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_usuarios_espacios_usuario_id");

                    b.ToTable("usuarios_espacios", (string)null);
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.Edificio", b =>
                {
                    b.HasBaseType("GateKeep.Api.Domain.Entities.Espacio");

                    b.Property<string>("CodigoEdificio")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NumeroPisos")
                        .HasColumnType("integer");

                    b.HasIndex("CodigoEdificio")
                        .IsUnique()
                        .HasDatabaseName("IX_edificios_codigo")
                        .HasFilter("\"CodigoEdificio\" IS NOT NULL");

                    b.ToTable("edificios", (string)null);
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.Laboratorio", b =>
                {
                    b.HasBaseType("GateKeep.Api.Domain.Entities.Espacio");

                    b.Property<long>("EdificioId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EquipamientoEspecial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("NumeroLaboratorio")
                        .HasColumnType("integer");

                    b.Property<string>("TipoLaboratorio")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasIndex("EdificioId")
                        .HasDatabaseName("IX_laboratorios_edificio_id");

                    b.HasIndex("EdificioId", "NumeroLaboratorio")
                        .IsUnique()
                        .HasDatabaseName("IX_laboratorios_edificio_numero");

                    b.ToTable("laboratorios", (string)null);
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.Salon", b =>
                {
                    b.HasBaseType("GateKeep.Api.Domain.Entities.Espacio");

                    b.Property<long>("EdificioId")
                        .HasColumnType("bigint");

                    b.Property<int>("NumeroSalon")
                        .HasColumnType("integer");

                    b.Property<string>("TipoSalon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasIndex("EdificioId")
                        .HasDatabaseName("IX_salones_edificio_id");

                    b.HasIndex("EdificioId", "NumeroSalon")
                        .IsUnique()
                        .HasDatabaseName("IX_salones_edificio_numero");

                    b.ToTable("salones", (string)null);
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.BeneficioUsuario", b =>
                {
                    b.HasOne("GateKeep.Api.Domain.Entities.Beneficio", null)
                        .WithMany()
                        .HasForeignKey("BeneficioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GateKeep.Api.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.EventoAcceso", b =>
                {
                    b.HasOne("GateKeep.Api.Domain.Entities.Espacio", null)
                        .WithMany()
                        .HasForeignKey("EspacioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GateKeep.Api.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.ReglaAcceso", b =>
                {
                    b.HasOne("GateKeep.Api.Domain.Entities.Espacio", null)
                        .WithMany()
                        .HasForeignKey("EspacioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.UsuarioEspacio", b =>
                {
                    b.HasOne("GateKeep.Api.Domain.Entities.Espacio", null)
                        .WithMany()
                        .HasForeignKey("EspacioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GateKeep.Api.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.Edificio", b =>
                {
                    b.HasOne("GateKeep.Api.Domain.Entities.Espacio", null)
                        .WithOne()
                        .HasForeignKey("GateKeep.Api.Domain.Entities.Edificio", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.Laboratorio", b =>
                {
                    b.HasOne("GateKeep.Api.Domain.Entities.Edificio", null)
                        .WithMany()
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GateKeep.Api.Domain.Entities.Espacio", null)
                        .WithOne()
                        .HasForeignKey("GateKeep.Api.Domain.Entities.Laboratorio", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GateKeep.Api.Domain.Entities.Salon", b =>
                {
                    b.HasOne("GateKeep.Api.Domain.Entities.Edificio", null)
                        .WithMany()
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GateKeep.Api.Domain.Entities.Espacio", null)
                        .WithOne()
                        .HasForeignKey("GateKeep.Api.Domain.Entities.Salon", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
